name: Linting and Type Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install pylint mypy streamlit opencv-python-headless ultralytics
    - name: Run Pylint
      run: pylint main.py --fail-under=5.0
    - name: Run Mypy
      run: mypy main.py
